# Development mode - hot reload for both frontend and backend
services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    env_file:
      - .env
    environment:
      - ENV=DEV
    ports:
      - "6006:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: build-stage
    container_name: angular_app
    environment:
      - ENV=DEV
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npx ng serve --host 0.0.0.0 --port 4200 --poll 2000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
