services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "6006:8000"  # FastAPI backend exposed on port 6006
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: angular_app
    ports:
      - "4200:80"  # Map host port 4200 to container port 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
